package com.demo.dao;

import com.demo.entity.Admin;
import com.demo.entity.User;

/**
 * @author 汪毅
 * 管理员Mapper
 *
 */
public interface AdminMapper {
   
	/**
	 * 管理员登录dao接口
	 * @param admin
	 * @return
	 */
	Admin login(Admin admin);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int updatePassword(Admin admin);
}