package com.demo.dao;

import java.util.List;
import java.util.Map;

import com.demo.entity.Checks;


/**
 * 考勤记录Dao
 *  
 * @YJC
 */
public interface ChecksMapper {
	
	/**
	 * 查询集合
	 * @param map
	 * @return
	 */
	List<Checks> find(Map<String,Object> map);
	
	/**
	 * 获取总记录数
	 * @param map
	 * @return
	 */
	Long getTotal(Map<String,Object> map);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     */
    int deleteByPrimaryKey(String checkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     */
    int insert(Checks checks);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     */
    int insertSelective(Checks checks);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     */
    Checks selectByPrimaryKey(String checkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     */
    int updateByPrimaryKeySelective(Checks checks);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     */
    int updateByPrimaryKey(Checks checks);
}