package com.demo.dao;

import com.demo.entity.Check;

public interface CheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String checkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbggenerated
     */
    int insert(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbggenerated
     */
    int insertSelective(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbggenerated
     */
    Check selectByPrimaryKey(String checkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Check record);
}