package com.demo.dao;

import com.demo.entity.Dormitory;

public interface DormitoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String dormitoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    int insert(Dormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    int insertSelective(Dormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    Dormitory selectByPrimaryKey(String dormitoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dormitory record);
}