package com.demo.dao;

import java.util.List;
import java.util.Map;

import com.demo.entity.Feedback;

public interface FeedbackMapper {
	
	/**
	 * 查询反馈信息集合
	 * @param map
	 * @return
	 */
	public List<Feedback> find(Map<String,Object> map);
	/**
	 * 获取反馈信息总记录数
	 * @param map
	 * @return
	 */
	public Long getTotal(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
	public int add(Feedback feeb);

}