package com.demo.dao;

import com.demo.entity.Hygiene;

public interface HygieneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String hygieneid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     *
     * @mbggenerated
     */
    int insert(Hygiene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     *
     * @mbggenerated
     */
    int insertSelective(Hygiene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     *
     * @mbggenerated
     */
    Hygiene selectByPrimaryKey(String hygieneid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Hygiene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hygiene record);
}