package com.demo.dao;

import java.util.List;
import java.util.Map;

import com.demo.entity.Hygiene;


/**
 * 卫生记录Dao
 * 
 * @YJC
 */
public interface HygieneMapper {
	
	/**
	 * 查询集合
	 * @param map
	 * @return
	 */
	List<Hygiene> find(Map<String,Object> map);
	
	/**
	 * 获取总记录数
	 * @param map
	 * @return
	 */
	Long getTotal(Map<String,Object> map);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     */
    int deleteByPrimaryKey(String hygieneid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     */
    int insert(Hygiene hygiene);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     */
    int insertSelective(Hygiene hygiene);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     */
    Hygiene selectByPrimaryKey(String hygieneid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     */
    int updateByPrimaryKeySelective(Hygiene hygiene);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hygiene
     */
    int updateByPrimaryKey(Hygiene hygiene);
}