package com.demo.dao;

import com.demo.entity.Student;
import com.demo.entity.Thing;

import java.util.List;
import java.util.Map;

/**
 * 学生信息dao
 * 
 * @author lc
 *
 */
public interface StudentMapper {

	/**
	 * 查询学生集合
	 * 
	 * @param map
	 * @return
	 */
	List<Student> find(Map<String, Object> map);

	/**
	 * 获取总记录数
	 * 
	 * @param map
	 * @return
	 */
	Long getTotal(Map<String, Object> map);

	/**
	 * 插入一条新的数据
	 * 
	 * @param record
	 * @return
	 */
	int add(Thing record);

	/**
	 * 以ID为准，更新数据
	 * 
	 * @param record
	 * @return
	 */
	int update(Thing record);

	/**
	 * 根据id查找实体
	 * 
	 * @param id
	 * @return
	 */
	Thing findById(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String studentid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated
	 */
	int insert(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated
	 */
	int insertSelective(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated
	 */
	Student selectByPrimaryKey(String studentid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table student
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Student record);
}