package com.demo.dao;

import java.util.List;
import java.util.Map;

import com.demo.entity.Thing;
/**
 * 公共物品管理Dao借口
 * @author jialiang
 *
 */
public interface ThingMapper {

    /**
	 * 查询物品集合
	 * @param map
	 * @return
	 */
    List<Thing> find(Map<String,Object> map);
	
    /**
	 * 获取总记录数
	 * @param map
	 * @return
	 */
	Long getTotal(Map<String,Object> map);
	
	  /**
     * 插入一条新的数据
     * @param record
     * @return
     */
    int add(Thing record);
	
	/**
	    * 以ID为准，更新数据
	    * @param record
	    * @return
	    */
	int update(Thing record);
	    
	
	
	/**
	 * 根据id查找实体
	 * @param id
	 * @return
	 */
	 Thing findById(Integer id);
	
	
	
	    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thing
     *
     * @mbggenerated
     */
    int insertSelective(Thing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thing
     *
     * @mbggenerated
     */
    Thing selectByPrimaryKey(String thingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thing
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Thing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String thingid);
}