package com.demo.entity;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbggenerated
     */
    private String adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminNo
     *
     * @mbggenerated
     */
    private String adminno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbggenerated
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPassword
     *
     * @mbggenerated
     */
    private String adminpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminAge
     *
     * @mbggenerated
     */
    private String adminage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminSex
     *
     * @mbggenerated
     */
    private String adminsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPosition
     *
     * @mbggenerated
     */
    private String adminposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPhone
     *
     * @mbggenerated
     */
    private String adminphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminDormitoryNo
     *
     * @mbggenerated
     */
    private String admindormitoryno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbggenerated
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbggenerated
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminNo
     *
     * @return the value of admin.adminNo
     *
     * @mbggenerated
     */
    public String getAdminno() {
        return adminno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminNo
     *
     * @param adminno the value for admin.adminNo
     *
     * @mbggenerated
     */
    public void setAdminno(String adminno) {
        this.adminno = adminno == null ? null : adminno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbggenerated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbggenerated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPassword
     *
     * @return the value of admin.adminPassword
     *
     * @mbggenerated
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPassword
     *
     * @param adminpassword the value for admin.adminPassword
     *
     * @mbggenerated
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword == null ? null : adminpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminAge
     *
     * @return the value of admin.adminAge
     *
     * @mbggenerated
     */
    public String getAdminage() {
        return adminage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminAge
     *
     * @param adminage the value for admin.adminAge
     *
     * @mbggenerated
     */
    public void setAdminage(String adminage) {
        this.adminage = adminage == null ? null : adminage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminSex
     *
     * @return the value of admin.adminSex
     *
     * @mbggenerated
     */
    public String getAdminsex() {
        return adminsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminSex
     *
     * @param adminsex the value for admin.adminSex
     *
     * @mbggenerated
     */
    public void setAdminsex(String adminsex) {
        this.adminsex = adminsex == null ? null : adminsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPosition
     *
     * @return the value of admin.adminPosition
     *
     * @mbggenerated
     */
    public String getAdminposition() {
        return adminposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPosition
     *
     * @param adminposition the value for admin.adminPosition
     *
     * @mbggenerated
     */
    public void setAdminposition(String adminposition) {
        this.adminposition = adminposition == null ? null : adminposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPhone
     *
     * @return the value of admin.adminPhone
     *
     * @mbggenerated
     */
    public String getAdminphone() {
        return adminphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPhone
     *
     * @param adminphone the value for admin.adminPhone
     *
     * @mbggenerated
     */
    public void setAdminphone(String adminphone) {
        this.adminphone = adminphone == null ? null : adminphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminDormitoryNo
     *
     * @return the value of admin.adminDormitoryNo
     *
     * @mbggenerated
     */
    public String getAdmindormitoryno() {
        return admindormitoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminDormitoryNo
     *
     * @param admindormitoryno the value for admin.adminDormitoryNo
     *
     * @mbggenerated
     */
    public void setAdmindormitoryno(String admindormitoryno) {
        this.admindormitoryno = admindormitoryno == null ? null : admindormitoryno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.remarks
     *
     * @return the value of admin.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.remarks
     *
     * @param remarks the value for admin.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}