package com.demo.entity;

public class Check {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkId
     *
     * @mbggenerated
     */
    private String checkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkFloor
     *
     * @mbggenerated
     */
    private String checkfloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkDormitoryNo
     *
     * @mbggenerated
     */
    private String checkdormitoryno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkContent
     *
     * @mbggenerated
     */
    private String checkcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.checkTime
     *
     * @mbggenerated
     */
    private String checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkId
     *
     * @return the value of check.checkId
     *
     * @mbggenerated
     */
    public String getCheckid() {
        return checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkId
     *
     * @param checkid the value for check.checkId
     *
     * @mbggenerated
     */
    public void setCheckid(String checkid) {
        this.checkid = checkid == null ? null : checkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkFloor
     *
     * @return the value of check.checkFloor
     *
     * @mbggenerated
     */
    public String getCheckfloor() {
        return checkfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkFloor
     *
     * @param checkfloor the value for check.checkFloor
     *
     * @mbggenerated
     */
    public void setCheckfloor(String checkfloor) {
        this.checkfloor = checkfloor == null ? null : checkfloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkDormitoryNo
     *
     * @return the value of check.checkDormitoryNo
     *
     * @mbggenerated
     */
    public String getCheckdormitoryno() {
        return checkdormitoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkDormitoryNo
     *
     * @param checkdormitoryno the value for check.checkDormitoryNo
     *
     * @mbggenerated
     */
    public void setCheckdormitoryno(String checkdormitoryno) {
        this.checkdormitoryno = checkdormitoryno == null ? null : checkdormitoryno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkContent
     *
     * @return the value of check.checkContent
     *
     * @mbggenerated
     */
    public String getCheckcontent() {
        return checkcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkContent
     *
     * @param checkcontent the value for check.checkContent
     *
     * @mbggenerated
     */
    public void setCheckcontent(String checkcontent) {
        this.checkcontent = checkcontent == null ? null : checkcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.checkTime
     *
     * @return the value of check.checkTime
     *
     * @mbggenerated
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.checkTime
     *
     * @param checktime the value for check.checkTime
     *
     * @mbggenerated
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime == null ? null : checktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.remarks
     *
     * @return the value of check.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.remarks
     *
     * @param remarks the value for check.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}