package com.demo.entity;

public class Checks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checks.checksId
     *
     * @mbggenerated
     */
    private String checksid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checks.checksFloor
     *
     * @mbggenerated
     */
    private String checksfloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checks.checksDormitoryNo
     *
     * @mbggenerated
     */
    private String checksdormitoryno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checks.checksContent
     *
     * @mbggenerated
     */
    private String checkscontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checks.checksTime
     *
     * @mbggenerated
     */
    private String checkstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checks.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checks.checksId
     *
     * @return the value of checks.checksId
     *
     * @mbggenerated
     */
    public String getChecksid() {
        return checksid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checks.checksId
     *
     * @param checksid the value for checks.checksId
     *
     * @mbggenerated
     */
    public void setChecksid(String checksid) {
        this.checksid = checksid == null ? null : checksid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checks.checksFloor
     *
     * @return the value of checks.checksFloor
     *
     * @mbggenerated
     */
    public String getChecksfloor() {
        return checksfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checks.checksFloor
     *
     * @param checksfloor the value for checks.checksFloor
     *
     * @mbggenerated
     */
    public void setChecksfloor(String checksfloor) {
        this.checksfloor = checksfloor == null ? null : checksfloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checks.checksDormitoryNo
     *
     * @return the value of checks.checksDormitoryNo
     *
     * @mbggenerated
     */
    public String getChecksdormitoryno() {
        return checksdormitoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checks.checksDormitoryNo
     *
     * @param checksdormitoryno the value for checks.checksDormitoryNo
     *
     * @mbggenerated
     */
    public void setChecksdormitoryno(String checksdormitoryno) {
        this.checksdormitoryno = checksdormitoryno == null ? null : checksdormitoryno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checks.checksContent
     *
     * @return the value of checks.checksContent
     *
     * @mbggenerated
     */
    public String getCheckscontent() {
        return checkscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checks.checksContent
     *
     * @param checkscontent the value for checks.checksContent
     *
     * @mbggenerated
     */
    public void setCheckscontent(String checkscontent) {
        this.checkscontent = checkscontent == null ? null : checkscontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checks.checksTime
     *
     * @return the value of checks.checksTime
     *
     * @mbggenerated
     */
    public String getCheckstime() {
        return checkstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checks.checksTime
     *
     * @param checkstime the value for checks.checksTime
     *
     * @mbggenerated
     */
    public void setCheckstime(String checkstime) {
        this.checkstime = checkstime == null ? null : checkstime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checks.remarks
     *
     * @return the value of checks.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checks.remarks
     *
     * @param remarks the value for checks.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}