package com.demo.entity;

public class Demo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.demo
     *
     * @mbggenerated
     */
    private String demo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.demo
     *
     * @return the value of demo.demo
     *
     * @mbggenerated
     */
    public String getDemo() {
        return demo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.demo
     *
     * @param demo the value for demo.demo
     *
     * @mbggenerated
     */
    public void setDemo(String demo) {
        this.demo = demo == null ? null : demo.trim();
    }
}