package com.demo.entity;

public class Dormitory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.dormitoryId
     *
     * @mbggenerated
     */
    private String dormitoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.dormitoryFloor
     *
     * @mbggenerated
     */
    private String dormitoryfloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.dormitoryNo
     *
     * @mbggenerated
     */
    private String dormitoryno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.dormitoryAllNum
     *
     * @mbggenerated
     */
    private String dormitoryallnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.dormitoryLiveNum
     *
     * @mbggenerated
     */
    private String dormitorylivenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.dormitoryId
     *
     * @return the value of dormitory.dormitoryId
     *
     * @mbggenerated
     */
    public String getDormitoryid() {
        return dormitoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.dormitoryId
     *
     * @param dormitoryid the value for dormitory.dormitoryId
     *
     * @mbggenerated
     */
    public void setDormitoryid(String dormitoryid) {
        this.dormitoryid = dormitoryid == null ? null : dormitoryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.dormitoryFloor
     *
     * @return the value of dormitory.dormitoryFloor
     *
     * @mbggenerated
     */
    public String getDormitoryfloor() {
        return dormitoryfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.dormitoryFloor
     *
     * @param dormitoryfloor the value for dormitory.dormitoryFloor
     *
     * @mbggenerated
     */
    public void setDormitoryfloor(String dormitoryfloor) {
        this.dormitoryfloor = dormitoryfloor == null ? null : dormitoryfloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.dormitoryNo
     *
     * @return the value of dormitory.dormitoryNo
     *
     * @mbggenerated
     */
    public String getDormitoryno() {
        return dormitoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.dormitoryNo
     *
     * @param dormitoryno the value for dormitory.dormitoryNo
     *
     * @mbggenerated
     */
    public void setDormitoryno(String dormitoryno) {
        this.dormitoryno = dormitoryno == null ? null : dormitoryno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.dormitoryAllNum
     *
     * @return the value of dormitory.dormitoryAllNum
     *
     * @mbggenerated
     */
    public String getDormitoryallnum() {
        return dormitoryallnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.dormitoryAllNum
     *
     * @param dormitoryallnum the value for dormitory.dormitoryAllNum
     *
     * @mbggenerated
     */
    public void setDormitoryallnum(String dormitoryallnum) {
        this.dormitoryallnum = dormitoryallnum == null ? null : dormitoryallnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.dormitoryLiveNum
     *
     * @return the value of dormitory.dormitoryLiveNum
     *
     * @mbggenerated
     */
    public String getDormitorylivenum() {
        return dormitorylivenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.dormitoryLiveNum
     *
     * @param dormitorylivenum the value for dormitory.dormitoryLiveNum
     *
     * @mbggenerated
     */
    public void setDormitorylivenum(String dormitorylivenum) {
        this.dormitorylivenum = dormitorylivenum == null ? null : dormitorylivenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.remarks
     *
     * @return the value of dormitory.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.remarks
     *
     * @param remarks the value for dormitory.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}