package com.demo.entity;

public class Hygiene {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hygiene.hygieneId
     *
     * @mbggenerated
     */
    private String hygieneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hygiene.hygieneFloor
     *
     * @mbggenerated
     */
    private String hygienefloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hygiene.hygieneDormitoryNo
     *
     * @mbggenerated
     */
    private String hygienedormitoryno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hygiene.hygieneContent
     *
     * @mbggenerated
     */
    private String hygienecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hygiene.hygieneGrade
     *
     * @mbggenerated
     */
    private String hygienegrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hygiene.hygieneTime
     *
     * @mbggenerated
     */
    private String hygienetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hygiene.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hygiene.hygieneId
     *
     * @return the value of hygiene.hygieneId
     *
     * @mbggenerated
     */
    public String getHygieneid() {
        return hygieneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hygiene.hygieneId
     *
     * @param hygieneid the value for hygiene.hygieneId
     *
     * @mbggenerated
     */
    public void setHygieneid(String hygieneid) {
        this.hygieneid = hygieneid == null ? null : hygieneid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hygiene.hygieneFloor
     *
     * @return the value of hygiene.hygieneFloor
     *
     * @mbggenerated
     */
    public String getHygienefloor() {
        return hygienefloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hygiene.hygieneFloor
     *
     * @param hygienefloor the value for hygiene.hygieneFloor
     *
     * @mbggenerated
     */
    public void setHygienefloor(String hygienefloor) {
        this.hygienefloor = hygienefloor == null ? null : hygienefloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hygiene.hygieneDormitoryNo
     *
     * @return the value of hygiene.hygieneDormitoryNo
     *
     * @mbggenerated
     */
    public String getHygienedormitoryno() {
        return hygienedormitoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hygiene.hygieneDormitoryNo
     *
     * @param hygienedormitoryno the value for hygiene.hygieneDormitoryNo
     *
     * @mbggenerated
     */
    public void setHygienedormitoryno(String hygienedormitoryno) {
        this.hygienedormitoryno = hygienedormitoryno == null ? null : hygienedormitoryno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hygiene.hygieneContent
     *
     * @return the value of hygiene.hygieneContent
     *
     * @mbggenerated
     */
    public String getHygienecontent() {
        return hygienecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hygiene.hygieneContent
     *
     * @param hygienecontent the value for hygiene.hygieneContent
     *
     * @mbggenerated
     */
    public void setHygienecontent(String hygienecontent) {
        this.hygienecontent = hygienecontent == null ? null : hygienecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hygiene.hygieneGrade
     *
     * @return the value of hygiene.hygieneGrade
     *
     * @mbggenerated
     */
    public String getHygienegrade() {
        return hygienegrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hygiene.hygieneGrade
     *
     * @param hygienegrade the value for hygiene.hygieneGrade
     *
     * @mbggenerated
     */
    public void setHygienegrade(String hygienegrade) {
        this.hygienegrade = hygienegrade == null ? null : hygienegrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hygiene.hygieneTime
     *
     * @return the value of hygiene.hygieneTime
     *
     * @mbggenerated
     */
    public String getHygienetime() {
        return hygienetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hygiene.hygieneTime
     *
     * @param hygienetime the value for hygiene.hygieneTime
     *
     * @mbggenerated
     */
    public void setHygienetime(String hygienetime) {
        this.hygienetime = hygienetime == null ? null : hygienetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hygiene.remarks
     *
     * @return the value of hygiene.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hygiene.remarks
     *
     * @param remarks the value for hygiene.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}