package com.demo.entity;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.noticeId
     *
     * @mbggenerated
     */
    private String noticeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.noticeType
     *
     * @mbggenerated
     */
    private String noticetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.noticeTitle
     *
     * @mbggenerated
     */
    private String noticetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.noticeAuthor
     *
     * @mbggenerated
     */
    private String noticeauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.noticeContent
     *
     * @mbggenerated
     */
    private String noticecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.noticeTime
     *
     * @mbggenerated
     */
    private String noticetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.noticeId
     *
     * @return the value of notice.noticeId
     *
     * @mbggenerated
     */
    public String getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.noticeId
     *
     * @param noticeid the value for notice.noticeId
     *
     * @mbggenerated
     */
    public void setNoticeid(String noticeid) {
        this.noticeid = noticeid == null ? null : noticeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.noticeType
     *
     * @return the value of notice.noticeType
     *
     * @mbggenerated
     */
    public String getNoticetype() {
        return noticetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.noticeType
     *
     * @param noticetype the value for notice.noticeType
     *
     * @mbggenerated
     */
    public void setNoticetype(String noticetype) {
        this.noticetype = noticetype == null ? null : noticetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.noticeTitle
     *
     * @return the value of notice.noticeTitle
     *
     * @mbggenerated
     */
    public String getNoticetitle() {
        return noticetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.noticeTitle
     *
     * @param noticetitle the value for notice.noticeTitle
     *
     * @mbggenerated
     */
    public void setNoticetitle(String noticetitle) {
        this.noticetitle = noticetitle == null ? null : noticetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.noticeAuthor
     *
     * @return the value of notice.noticeAuthor
     *
     * @mbggenerated
     */
    public String getNoticeauthor() {
        return noticeauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.noticeAuthor
     *
     * @param noticeauthor the value for notice.noticeAuthor
     *
     * @mbggenerated
     */
    public void setNoticeauthor(String noticeauthor) {
        this.noticeauthor = noticeauthor == null ? null : noticeauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.noticeContent
     *
     * @return the value of notice.noticeContent
     *
     * @mbggenerated
     */
    public String getNoticecontent() {
        return noticecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.noticeContent
     *
     * @param noticecontent the value for notice.noticeContent
     *
     * @mbggenerated
     */
    public void setNoticecontent(String noticecontent) {
        this.noticecontent = noticecontent == null ? null : noticecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.noticeTime
     *
     * @return the value of notice.noticeTime
     *
     * @mbggenerated
     */
    public String getNoticetime() {
        return noticetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.noticeTime
     *
     * @param noticetime the value for notice.noticeTime
     *
     * @mbggenerated
     */
    public void setNoticetime(String noticetime) {
        this.noticetime = noticetime == null ? null : noticetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.remarks
     *
     * @return the value of notice.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.remarks
     *
     * @param remarks the value for notice.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}