package com.demo.entity;

import java.util.Date;

public class Student {
	 /**
     * 学生id
     *
     * @mbggenerated
     */
    private String studentid;

    /**
     * 学生学号
     *
     * @mbggenerated
     */
    private String studentno;

    /**
     * 学生密码
     *
     * @mbggenerated
     */
    private String studentpassword;

    /**
     *学生名字
     *
     * @mbggenerated
     */
    private String studentname;

    /**
     *学生性别
     *
     * @mbggenerated
     */
    private String studentsex;

    /**
     *学生寝室
     *
     * @mbggenerated
     */
    private String studentdormitoryno;

    /**
     * 床铺
     * @mbggenerated
     */
    private String studentbed;

    /**
     * 学生年龄
     *
     * @mbggenerated
     */
    private String studentage;

    /**
     *学生电话
     *
     * @mbggenerated
     */
    private String studentphone;

    /**
     * 学生专业
     *
     * @mbggenerated
     */
    private String studentmajor;

    /**
     * 学生学院
     *
     * @mbggenerated
     */
    private String studentcollege;

    /**
     *入住时间
     * @mbggenerated
     */
    private String studenttime;

    /**
     * 描述
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentId
     *
     * @return the value of student.studentId
     *
     * @mbggenerated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentId
     *
     * @param studentid the value for student.studentId
     *
     * @mbggenerated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentNo
     *
     * @return the value of student.studentNo
     *
     * @mbggenerated
     */
    public String getStudentno() {
        return studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentNo
     *
     * @param studentno the value for student.studentNo
     *
     * @mbggenerated
     */
    public void setStudentno(String studentno) {
        this.studentno = studentno == null ? null : studentno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentPassword
     *
     * @return the value of student.studentPassword
     *
     * @mbggenerated
     */
    public String getStudentpassword() {
        return studentpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentPassword
     *
     * @param studentpassword the value for student.studentPassword
     *
     * @mbggenerated
     */
    public void setStudentpassword(String studentpassword) {
        this.studentpassword = studentpassword == null ? null : studentpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentName
     *
     * @return the value of student.studentName
     *
     * @mbggenerated
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentName
     *
     * @param studentname the value for student.studentName
     *
     * @mbggenerated
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname == null ? null : studentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentSex
     *
     * @return the value of student.studentSex
     *
     * @mbggenerated
     */
    public String getStudentsex() {
        return studentsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentSex
     *
     * @param studentsex the value for student.studentSex
     *
     * @mbggenerated
     */
    public void setStudentsex(String studentsex) {
        this.studentsex = studentsex == null ? null : studentsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentDormitoryNo
     *
     * @return the value of student.studentDormitoryNo
     *
     * @mbggenerated
     */
    public String getStudentdormitoryno() {
        return studentdormitoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentDormitoryNo
     *
     * @param studentdormitoryno the value for student.studentDormitoryNo
     *
     * @mbggenerated
     */
    public void setStudentdormitoryno(String studentdormitoryno) {
        this.studentdormitoryno = studentdormitoryno == null ? null : studentdormitoryno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentBed
     *
     * @return the value of student.studentBed
     *
     * @mbggenerated
     */
    public String getStudentbed() {
        return studentbed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentBed
     *
     * @param studentbed the value for student.studentBed
     *
     * @mbggenerated
     */
    public void setStudentbed(String studentbed) {
        this.studentbed = studentbed == null ? null : studentbed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentAge
     *
     * @return the value of student.studentAge
     *
     * @mbggenerated
     */
    public String getStudentage() {
        return studentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentAge
     *
     * @param studentage the value for student.studentAge
     *
     * @mbggenerated
     */
    public void setStudentage(String studentage) {
        this.studentage = studentage == null ? null : studentage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentPhone
     *
     * @return the value of student.studentPhone
     *
     * @mbggenerated
     */
    public String getStudentphone() {
        return studentphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentPhone
     *
     * @param studentphone the value for student.studentPhone
     *
     * @mbggenerated
     */
    public void setStudentphone(String studentphone) {
        this.studentphone = studentphone == null ? null : studentphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentMajor
     *
     * @return the value of student.studentMajor
     *
     * @mbggenerated
     */
    public String getStudentmajor() {
        return studentmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentMajor
     *
     * @param studentmajor the value for student.studentMajor
     *
     * @mbggenerated
     */
    public void setStudentmajor(String studentmajor) {
        this.studentmajor = studentmajor == null ? null : studentmajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentCollege
     *
     * @return the value of student.studentCollege
     *
     * @mbggenerated
     */
    public String getStudentcollege() {
        return studentcollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentCollege
     *
     * @param studentcollege the value for student.studentCollege
     *
     * @mbggenerated
     */
    public void setStudentcollege(String studentcollege) {
        this.studentcollege = studentcollege == null ? null : studentcollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentTime
     *
     * @return the value of student.studentTime
     *
     * @mbggenerated
     */
    public String getStudenttime() {
        return studenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentTime
     *
     * @param studenttime the value for student.studentTime
     *
     * @mbggenerated
     */
    public void setStudenttime(String studenttime) {
        this.studenttime = studenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.remarks
     *
     * @return the value of student.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.remarks
     *
     * @param remarks the value for student.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}