package com.demo.entity;

public class Thing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thing.thingId
     *
     * @mbggenerated
     */
    private String thingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thing.thingNo
     *
     * @mbggenerated
     */
    private String thingno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thing.thingName
     *
     * @mbggenerated
     */
    private String thingname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thing.thingType
     *
     * @mbggenerated
     */
    private String thingtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thing.thingState
     *
     * @mbggenerated
     */
    private String thingstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thing.thingDormitory
     *
     * @mbggenerated
     */
    private String thingdormitory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thing.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thing.thingId
     *
     * @return the value of thing.thingId
     *
     * @mbggenerated
     */
    public String getThingid() {
        return thingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thing.thingId
     *
     * @param thingid the value for thing.thingId
     *
     * @mbggenerated
     */
    public void setThingid(String thingid) {
        this.thingid = thingid == null ? null : thingid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thing.thingNo
     *
     * @return the value of thing.thingNo
     *
     * @mbggenerated
     */
    public String getThingno() {
        return thingno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thing.thingNo
     *
     * @param thingno the value for thing.thingNo
     *
     * @mbggenerated
     */
    public void setThingno(String thingno) {
        this.thingno = thingno == null ? null : thingno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thing.thingName
     *
     * @return the value of thing.thingName
     *
     * @mbggenerated
     */
    public String getThingname() {
        return thingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thing.thingName
     *
     * @param thingname the value for thing.thingName
     *
     * @mbggenerated
     */
    public void setThingname(String thingname) {
        this.thingname = thingname == null ? null : thingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thing.thingType
     *
     * @return the value of thing.thingType
     *
     * @mbggenerated
     */
    public String getThingtype() {
        return thingtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thing.thingType
     *
     * @param thingtype the value for thing.thingType
     *
     * @mbggenerated
     */
    public void setThingtype(String thingtype) {
        this.thingtype = thingtype == null ? null : thingtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thing.thingState
     *
     * @return the value of thing.thingState
     *
     * @mbggenerated
     */
    public String getThingstate() {
        return thingstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thing.thingState
     *
     * @param thingstate the value for thing.thingState
     *
     * @mbggenerated
     */
    public void setThingstate(String thingstate) {
        this.thingstate = thingstate == null ? null : thingstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thing.thingDormitory
     *
     * @return the value of thing.thingDormitory
     *
     * @mbggenerated
     */
    public String getThingdormitory() {
        return thingdormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thing.thingDormitory
     *
     * @param thingdormitory the value for thing.thingDormitory
     *
     * @mbggenerated
     */
    public void setThingdormitory(String thingdormitory) {
        this.thingdormitory = thingdormitory == null ? null : thingdormitory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thing.remark
     *
     * @return the value of thing.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thing.remark
     *
     * @param remark the value for thing.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}